version: '3.8'
name: 'dev-stage-server'

services:
  postgresql:
    image: bitnami/postgresql:14.17.0
    ports:
      - '${DATABASE_PORT}:5432'
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_DB_NAME}

  redis:
    image: bitnami/redis:7.4.3
    ports:
      - '${REDIS_PORT}:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
